name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Personal access token stored as repository secret
          token: ${{ secrets.RELEASE_PLEASE_TOKEN_SECRET }}
          release-type: node
